# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2.1

variables:
  restore_cache: &restore_cache
    restore_cache:
      keys:
        - miniconda-{{ checksum ".circleci/config.yml" }}-{{ arch }}
  save_cache: &save_cache
    save_cache:
      key: miniconda-{{ checksum ".circleci/config.yml" }}-{{ arch }}
      paths:
        - $HOME/miniconda

orbs:
  win: circleci/windows@2.2.0

install_pandoc: &install_pandoc
  name: Install pandoc
  command: |
    sudo apt-get update
    sudo apt-get install build-essential pandoc

setup_conda: &setup_conda
  name: Install miniconda
  command: |
    export MINICONDA=$HOME/miniconda
    echo "export PATH=$MINICONDA/bin:$PATH" >> $BASH_ENV
    source $BASH_ENV
    hash -r
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -f -p $MINICONDA
    conda config --set always_yes yes
    conda update conda
    conda info -a
    rm miniconda.sh

make_env: &make_env
  name: Make workshop environment
  command: |
    conda env create -n astropy-workshop --file 00-Install_and_Setup/environment.yml
    conda activate astropy-workshop
    python -m ipykernel install --user --name astropy-workshop

jobs:
  test_linux:
    machine: true
    steps:
      - run: *install_pandoc
      - run: *setup_conda
      - run: *make_env
      - checkout
      # TODO: run the tests

  # test_macos:
  #   macos:
  #     xcode: "10.0.0"
  #   steps:
  #     - run: *install_pandoc
  #     - run: *setup_conda
  #     - run: *make_env
  #     - checkout
  #     # TODO: run the tests

  # TODO: fill out the windows build. I'm not sure how to set up conda on
  # windows via circleci...
  test_windows:
    executor:
      name: win/default
    steps:
      - checkout

workflows:
  version: 2
  default:
    jobs:
      - test_linux
      - test_macos
