name: astropy-workshop

channels:
  - astropy

dependencies:
  - pip
  - python=3.8
  - ipython>=7.17
  - cython
  - jupyter
  - notebook>=6.0
  - jupyter-offlinenotebook
  - numpy>=1.16
  - scipy>=1.5
  - scikit-image>=0.17
  - matplotlib>=3.2
  - pandas>=1.0
  - pip:
    - pytest
    - beautifulsoup4
    - keyring
    - html5lib
    - xlwt
    - requests
    - jupyterlab
    - nbzip
    - nbgitpuller
    - "astropy>=4.2"
    - asdf
    - "gwcs>=0.16"
    - "photutils>=1.0.1"
    - "specutils>=1.0"
    - astroquery
